"""add reply_to_message_id to messages

Revision ID: 9ff6349a3fd5
Revises: 4f95db83189d
Create Date: 2026-02-16 15:14:14.790224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff6349a3fd5'
down_revision: Union[str, None] = '4f95db83189d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True))
    op.create_index('ix_messages_reply_to', 'messages', ['reply_to_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_reply_to', table_name='messages')
    op.drop_column('messages', 'reply_to_message_id')
    # ### end Alembic commands ###
